name: Terraform Plan (PR)

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      dev: ${{ steps.filter.outputs.dev }}
      stage: ${{ steps.filter.outputs.stage }}
      prod: ${{ steps.filter.outputs.prod }}
      modules: ${{ steps.filter.outputs.modules }}

    steps:
      - uses: actions/checkout@v4

      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dev:
              - 'envs/dev/**'
            stage:
              - 'envs/stage/**'
            prod:
              - 'envs/prod/**'
            modules:
              - 'modules/**'

  plan-dev:
    needs: detect-changes
    if: needs.detect-changes.outputs.dev == 'true' || needs.detect-changes.outputs.modules == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Plan (dev)
        working-directory: envs/dev
        run: terraform plan -var-file=dev.tfvars

  plan-stage:
    needs: detect-changes
    if: needs.detect-changes.outputs.stage == 'true' || needs.detect-changes.outputs.modules == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Plan (stage)
        working-directory: envs/stage
        run: terraform plan -var-file=stage.tfvars

  plan-prod:
    needs: detect-changes
    if: needs.detect-changes.outputs.prod == 'true' || needs.detect-changes.outputs.modules == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Plan (prod)
        working-directory: envs/prod
        run: terraform plan -var-file=prod.tfvars
